test_login_with_valid_data[mona.lisa@lelouvre.fr-mona@Davensi123-Mona Lisa],"('..\\..\\..\\Users\\kych\\.virtualenvs\\AutoTest-bc-6-ZuI\\Lib\\site-packages\\pytest_bdd\\scenario.py', 216, 'test_login_with_valid_data[mona.lisa@lelouvre.fr-mona@Davensi123-Mona Lisa]')",<Module test_login.py>,C:\Mydata\Proj-Danvesi\AutoTest\step_defs\test_login.py,<_pytest.config.Config object at 0x000001DA55C76950>
test_login_with_invalid_username_or_invalid_password[my.vo@dirox.net-klsjksldjf-user not found],"('..\\..\\..\\Users\\kych\\.virtualenvs\\AutoTest-bc-6-ZuI\\Lib\\site-packages\\pytest_bdd\\scenario.py', 216, 'test_login_with_invalid_username_or_invalid_password[my.vo@dirox.net-klsjksldjf-user not found]')",<Module test_login.py>,C:\Mydata\Proj-Danvesi\AutoTest\step_defs\test_login.py,<_pytest.config.Config object at 0x000001DA55C76950>
test_expect_a_response_after_event,"('..\\..\\..\\Users\\kych\\.virtualenvs\\AutoTest-bc-6-ZuI\\Lib\\site-packages\\pytest_bdd\\scenario.py', 216, 'test_expect_a_response_after_event')",<Module test_reqIntercept.py>,C:\Mydata\Proj-Danvesi\AutoTest\step_defs\test_reqIntercept.py,<_pytest.config.Config object at 0x000001DA55C76950>
test_nofeaturefile[chromium],"('step_defs\\test_withoutfeature.py', 34, 'test_nofeaturefile[chromium]')",<Module test_withoutfeature.py>,C:\Mydata\Proj-Danvesi\AutoTest\step_defs\test_withoutfeature.py,<_pytest.config.Config object at 0x000001DA55C76950>
